services:
  ollama:
    image: ollama/ollama
    container_name: ollama
    ports:
      - "11434:11434"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  rag:
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      - OLLAMA_ORIGINS=http://ollama:11434
    container_name: rag
    ports: 
      - "8001:8001"
    depends_on:
      - ollama